/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package slack.tf;

import com.slack.api.bolt.socket_mode.SocketModeApp;

public class App {
    public static void main(String[] args) throws Exception {

        var app = new com.slack.api.bolt.App();
        app.command("/tf-help", (req, ctx) -> {
            return ctx.ack(":wave: how can i help u?");
        });
        var appToken = System.getenv("SLACK_APP_TOKEN"); // only need app token to init connection
        var socketModeApp = new SocketModeApp(appToken, app);
        socketModeApp.start();
    }
}
